#pragma once

#include "CoreMinimal.h"

struct FCVXGPUPersistentFieldStats
{
    uint32 ResetSerial = 0;
    uint32 AllocatedPages = 0;
    uint32 PageCapacity = 0;
    uint32 HashCapacity = 0;
    uint32 PendingPatches = 0;
    uint32 CacheFullEvents = 0;
    uint64 CoalescedChunkReplacements = 0;
    uint64 SubmittedDeltaPackets = 0;
    uint64 SubmittedDeltaBytes = 0;
    uint64 DrainedPatchBytes = 0;
};

class CICADAVOXELRENDER_API FCVXGPUPageUploadBridge
{
public:
    // Fixed, bounded hot residency pool.
    // One page = 64 mm. A page stores 64 x 16 mm chunk summaries and exact 1 mm
    // occupancy masks only in the GPU cache representation.
    static constexpr uint32 PageCapacity = 4096u;
    static constexpr uint32 HashCapacity = 8192u; // power-of-two, 2x load headroom

    // Patch layout:
    // [0] op: 1=CLEAR_PAGE, 2=UPDATE_CHUNK
    // [1] page slot
    // [2] hash index
    // [3] local chunk [0..63]
    // [4..6] page XYZ
    // [7] reserved
    // [8..11] 4 packed 2-bit block-state words
    // [12..139] 64 x uint64 exact block masks as low/high uints
    static constexpr uint32 PatchStrideWords = 140u;

    static constexpr uint32 PageHashWords = HashCapacity * 4u;
    static constexpr uint32 PageMetaWords = PageCapacity * 4u;
    static constexpr uint32 ChunkStateWords = PageCapacity * 64u * 4u;
    static constexpr uint32 BlockMaskWords = PageCapacity * 64u * 64u * 2u;

    static void ResetPersistentField(uint32 OwnerId);

    // Accepts the existing CVX4 compact edit packet generated by the sparse world.
    // The bridge performs page-slot allocation and coalesces repeated chunk changes
    // before the render graph sees them. No render command is enqueued per edit.
    static void SubmitDeltaWords(const TArray<uint32>& Words);

    // Called on the render thread by the direct-field view extension once per frame.
    static void DrainCoalescedPatchWords(
        TArray<uint32>& OutWords,
        uint32& OutPatchCount);

    static FCVXGPUPersistentFieldStats GetPersistentFieldStats();
};
